[package]
name = "scnr2-python"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Python bindings for the scnr2 scanner crate"

[lib]
name = "scnr2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module"] }
scnr2 = { path = "../scnr2" }
scnr2_generate = { path = "../scnr2_generate" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"

[features]
default = []
dynamic-state = ["scnr2/dynamic-state", "scnr2_generate/dynamic-state"]
