[package]
name = "scnr2_macro"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
description = "Scanner/Lexer with regex patterns and multiple modes"
repository = "https://github.com/jsinger67/scnr2"

[dependencies]
scnr2_generate = { path = "../scnr2_generate", version = "0.5.1", default-features = false }

[features]
default = []
dynamic-state = ["scnr2_generate/dynamic-state"]

[lib]
bench = false
proc-macro = true
