[package]
name = "scnr2_macro"
version.workspace = true
edition.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
description = "Scanner/Lexer with regex patterns and multiple modes"
repository = "https://github.com/jsinger67/scnr2"

[features]
default = []
dynamic-state = ["scnr2_generate/dynamic-state"]

[dependencies]
scnr2_generate = { path = "../scnr2_generate", version = "0.3.3"  }

[lib]
bench = false
proc-macro = true
