[package]
edition = { workspace = true }
name = "tests"
publish = false
version = "0.1.0"

[dependencies]
scnr2 = { path = "../scnr2", default-features = false }
scnr2_generate = { path = "../scnr2_generate", default-features = false }

[features]
default = []
dynamic-state = ["scnr2/dynamic-state", "scnr2_generate/dynamic-state"]

[dev-dependencies]
codspeed-criterion-compat = "4.5.0"
criterion = "0.8.2"
env_logger = "0.11.10"
trybuild = "1.0"

[package.metadata.release]
release = false

[[bench]]
harness = false
name = "bench"

[[test]]
name = "match_test"
path = "match_test.rs"

[[test]]
name = "match_fuzz"
path = "match_fuzz.rs"

[[test]]
name = "match_errors"
path = "match_errors.rs"

[[test]]
name = "dynamic_state_test"
path = "dynamic_state_test.rs"
required-features = ["dynamic-state"]
