[package]
name = "scnr2_generate"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
description = "Scanner/Lexer with regex patterns and multiple modes"
repository = "https://github.com/jsinger67/scnr2"

[dependencies]
log = "0.4.29"
proc-macro2 = "1.0.106"
quote = "1.0.45"
regex-syntax = "0.8.10"
rustc-hash = "2.1.2"
syn = "2.0.117"

[features]
default = []
dynamic-state = []

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3.27.0"
